### ISSUE TITLE
Filename fix appears unnecessary

### ISSUE THREAD

**Issue by relud** [mozilla-services/fx-crash-sig#87]
module is modified from debug_file to filename as reported in the crash ping:
https://github.com/mozilla/fx-crash-sig/blob/f77f29cb4c279c46c8e11d73b61ee35f798878d7/fx_crash_sig/symbolicate.py#L210-L218

but I think eliot returns the correct thing:
https://github.com/mozilla-services/eliot/blob/224932dc33c73480ee80096ed30b15fb5ace27a6/eliot/symbolicate_resource.py#L510
https://github.com/mozilla-services/eliot/blob/224932dc33c73480ee80096ed30b15fb5ace27a6/eliot/symbolicate_resource.py#L370
https://github.com/mozilla-services/eliot/blob/224932dc33c73480ee80096ed30b15fb5ace27a6/eliot/libsymbolic.py#L39-L67

because when i copied that logic I'm getting `xul.dll` as module, not `xul.pdb`

**Comment by relud** [comment]
nevermind, i think i see how i misunderstood

**Comment by willkg** [comment]
I know I fixed a bunch of symbolication issues like this when I implemented Eliot. I think this is fixed in Eliot in [bug 1699546](https://bugzilla.mozilla.org/show_bug.cgi?id=1699546).
